createuser: implement Slurm user creation
using `allusers` as the default account

also, add Hydra clusters (for testing)

diff --git a/createuser b/createuser
--- a/createuser
+++ b/createuser
@@ -6,6 +6,7 @@ export LC_ALL=C
 
 cluster_name="${CLUSTER_NAME:-}"
 SGE_ACL=""
+slurm_account=""
 
 # Make sure we have a userid to create
 if [ "$#" -ne "1" ];
@@ -44,9 +45,14 @@ fi
 case "$cluster_name" in
     "kathleen")
         SGE_ACL="Open"
+        slurm_account="allusers"
         ;;
     "myriad")
         SGE_ACL="Open"
+        slurm_account="allusers"
+        ;;
+    dev-*)
+        slurm_account="allusers"
         ;;
     "michael"|"young")
         echo "Error: this is not the correct way to add users to the Thomas and Michael clusters." >&2
@@ -60,15 +66,21 @@ esac
 
 echo "creating account for $1"
 if command -v qconf >/dev/null; then
+    if [[ -z "$SGE_ACL" ]]; then
+        echo "Error: detected SGE, but this cluster is not supposed to run SGE." >&2
+        exit 1
+    fi
     qconf -au "$1" "$SGE_ACL"
 elif command -v sacctmgr >/dev/null; then
-    echo "Slurm user adding is not yet implemented since the details of cluster implementation have not yet been finalised."
-    echo "You'll need the sacctmgr command, probably something like this:"
-    echo ""
-    echo "  sacctmgr add user name=\"\$username\""
-    echo ""
-    echo "You'll also need at least Operator privileges on Slurm. (Or sudo access to get them.)"
-    exit 1
+    if [[ -z "${slurm_account}" ]]; then
+        echo "Error: detected Slurm, but this cluster is not supposed to run Slurm." >&2
+        exit 1
+    fi
+    sacctmgr --immediate --quiet add user name="${username}" defaultaccount="${slurm_account}"
+    if [[ $? -ne 0 ]]; then
+        echo "Error: could not add Slurm user - are you a Slurm operator?" >&2
+        exit 1
+    fi
 else
     echo "Error: no mechanism for adding users found." >&2
     exit 1
