createuser: fix error message, Thomas -> Young

diff --git a/createuser b/createuser
--- a/createuser
+++ b/createuser
@@ -55,7 +55,7 @@ case "$cluster_name" in
         slurm_account="allusers"
         ;;
     "michael"|"young")
-        echo "Error: this is not the correct way to add users to the Thomas and Michael clusters." >&2
+        echo "Error: this is not the correct way to add users to the Young and Michael clusters." >&2
         exit 1
         ;;
     *)
