Linting fixes on transfergold and create*user scripts

diff --git a/mmm/createMichaeluser b/mmm/createMichaeluser
--- a/mmm/createMichaeluser
+++ b/mmm/createMichaeluser
@@ -53,7 +53,7 @@ while getopts ":hu:e:k:nm:c:" opt; do
 done
 
 # make sure all arguments are supplied (checks for unset or empty)
-if [ ! "$username" ] || [ ! "$email" ] || [ ! "$ssh_key" ]
+if [[ ! "$username" ]] || [[ ! "$email" ]] || [[ ! "$ssh_key" ]]
 then
   usage
   exit 1
@@ -77,14 +77,14 @@ fi
 # replacement for become - creates homedir and adds key
 if ! sudo /shared/ucl/sysops/libexec/add_sshkeys "${username}" "${ssh_key}"
 then
-  echo $(date) ": Creation of ${username} homedir or addition of key failed, exiting." >&2
+  echo "$(date) : Creation of ${username} homedir or addition of key failed, exiting." >&2
   exit 1
 fi
 
 # add user to ACL so they can log in and submit jobs
 if ! qconf -au "$username" "$ACL"
 then
-  echo $(date) ": Adding ${username} to $ACL ACL failed, exiting." >&2
+  echo "$(date) : Adding ${username} to $ACL ACL failed, exiting." >&2
   exit 1
 fi
 
@@ -92,18 +92,17 @@ fi
 # Try 3 times.
 for i in 1 2 3
 do
-  qconf -su "$ACL" | grep -q "$username"
-  if [ $? == 0 ]
+  if qconf -su "$ACL" | grep -q "$username"
   then
     echo ""
-    echo $(date) ": Successfully allowed ${username} to log in"
+    echo "$(date) : Successfully allowed ${username} to log in"
     break
-  elif (( $i < 3 ))
+  elif [[ "$i" -lt 3 ]]
   # failed, try again
   then
     sleep 5
   else
-    echo $(date) ": Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk" >&2
+    echo "$(date) : Grid Engine failed to add ${username} to $ACL ACL three times - please contact rc-support@ucl.ac.uk" >&2
     exit 1
   fi
 done
@@ -118,7 +117,7 @@ Subject: subscribe address=${email}
 EOF
 
 # email welcome to user, unless do_not_mail was set
-if [ ! "$do_not_mail" ] 
+if [[ ! "$do_not_mail" ]] 
 then
   echo "  Emailing user ${username} at ${email}"
   /usr/sbin/sendmail -t<<EOF
